-- =====================================================
-- ÉTAPE 2B: AJOUTER LES COLONNES MANQUANTES
-- Exécutez ceci AVANT la Partie 3 (RLS)
-- =====================================================

-- Ajouter colonnes manquantes à quotes
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS share_token VARCHAR(255);
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS user_id UUID;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS client_id UUID;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS quote_number VARCHAR(50);
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS client_name VARCHAR(255);
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS client_email VARCHAR(255);
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS client_address TEXT;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS items JSONB DEFAULT '[]';
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS total_ht DECIMAL(12,2) DEFAULT 0;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS total_tva DECIMAL(12,2) DEFAULT 0;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS total_ttc DECIMAL(12,2) DEFAULT 0;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS validity_days INTEGER DEFAULT 30;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS signed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS signature_data TEXT;

-- Ajouter colonnes manquantes à invoices
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS share_token VARCHAR(255);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS user_id UUID;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS client_id UUID;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS quote_id UUID;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS invoice_number VARCHAR(50);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS client_name VARCHAR(255);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS client_email VARCHAR(255);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS client_address TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS items JSONB DEFAULT '[]';
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS total_ht DECIMAL(12,2) DEFAULT 0;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS total_tva DECIMAL(12,2) DEFAULT 0;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS total_ttc DECIMAL(12,2) DEFAULT 0;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS payment_status VARCHAR(50) DEFAULT 'unpaid';
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS paid_amount DECIMAL(12,2) DEFAULT 0;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS paid_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS due_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS notes TEXT;

-- Ajouter colonnes manquantes à clients
ALTER TABLE clients ADD COLUMN IF NOT EXISTS user_id UUID;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS company_name VARCHAR(255);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS contact_name VARCHAR(255);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS postal_code VARCHAR(20);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS country VARCHAR(100) DEFAULT 'France';
ALTER TABLE clients ADD COLUMN IF NOT EXISTS siret VARCHAR(50);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS tva_number VARCHAR(50);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS notes TEXT;

-- Ajouter colonnes manquantes à users
ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_plan VARCHAR(50) DEFAULT 'trial';
ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_status VARCHAR(50) DEFAULT 'active';
ALTER TABLE users ADD COLUMN IF NOT EXISTS trial_status VARCHAR(50) DEFAULT 'trial';
ALTER TABLE users ADD COLUMN IF NOT EXISTS trial_started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE users ADD COLUMN IF NOT EXISTS trial_ends_at TIMESTAMP WITH TIME ZONE DEFAULT (NOW() + INTERVAL '7 days');
ALTER TABLE users ADD COLUMN IF NOT EXISTS quote_limit INTEGER DEFAULT 5;
ALTER TABLE users ADD COLUMN IF NOT EXISTS invoice_limit INTEGER DEFAULT 5;
ALTER TABLE users ADD COLUMN IF NOT EXISTS quotes_created INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS invoices_created INTEGER DEFAULT 0;

SELECT 'Colonnes ajoutées avec succès!' as status;
